### ISSUE TITLE
Observation space of a maze

### ISSUE THREAD

**Issue by smiszym** [ParrotPrediction/openai-envs#6]
I agree that the action space is Discrete(8) - there are eight possible directions that an agent can choose from.

But observation space also being Discrete(8) confuses me: there are apparently 2^8 different observations, because each of the eight adjacent cells may be either a path or a wall. (to be precise one of the cells may contain a reward, which gives us additional 8 observations)

I believe we should use a custom Space class (`MazeObservationSpace`), similar to MultiBinary (https://github.com/openai/gym/blob/master/gym/spaces/multi_binary.py), but with `str` objects as observations instead of `array`

I can implement and submit a pull request if you agree.

https://github.com/ParrotPrediction/openai-envs/blob/f42c44068b14d3e935e6e299b173935e30d8d4b1/gym_maze/envs/abstract_maze.py#L25

**Comment by khozzy** [comment]
Yep, I think it's a great point.
Didn't saw any examples of creating custom observation spaces before.

Please do so.
